In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Model, Sequential
from tensorflow.keras.layers import Convolution2D,MaxPooling2D,ZeroPadding2D,Dense
from tensorflow.keras.layers import Dense, Flatten, BatchNormalization, Dropout,Softmax, Activation
from tensorflow.keras.preprocessing.image import load_img,img_to_array
from tensorflow.keras.applications.imagenet_utils import preprocess_input
import tensorflow.keras.backend as k
import cv2
import matplotlib.pyplot as plt
import os
import PIL
from keras.preprocessing.image import ImageDataGenerator

Using TensorFlow backend.


In [2]:
import os
os.chdir("D:\\MySQL\\image\\celeb_faces_images_train")
base_dir = os.getcwd()
base_dir

'D:\\MySQL\\image\\celeb_faces_images_train'

In [3]:
#create model
model = Sequential()
#add model layers
model.add(ZeroPadding2D((1,1),input_shape=(128,128, 3)))
#model.add(Convolution2D(64, (3,3), activation='relu', input_shape=(128,128,1)))
model.add(Convolution2D(32, (3,3), activation='relu'))
model.add(ZeroPadding2D((1,1)))
model.add(Convolution2D(128, (3, 3), activation='relu'))
model.add(MaxPooling2D((2,2), strides=(2,2)))
model.add(Flatten())
model.add(Dense(units=5,kernel_initializer='glorot_uniform',activation='softmax'))

In [28]:

#create model
model = Sequential()
#add model layers
model.add(Dense(input_shape=(128,128, 3),activation = 'relu'))
#model.add(Convolution2D(64, (3,3), activation='relu', input_shape=(128,128,1)))
#model.add(Convolution2D(32, (3,3), activation='relu'))
#model.add(ZeroPadding2D((1,1)))
#model.add(Convolution2D(128, (3, 3), activation='relu'))
#model.add(MaxPooling2D((2,2), strides=(2,2)))
#model.add(Flatten())
model.add(Dense(units=5,kernel_initializer='glorot_uniform',activation='softmax'))



TypeError: __init__() missing 1 required positional argument: 'units'

In [25]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 128, 128, 32)      128       
_________________________________________________________________
dense_4 (Dense)              (None, 128, 128, 5)       165       
Total params: 293
Trainable params: 293
Non-trainable params: 0
_________________________________________________________________


In [6]:
images_path = base_dir

In [11]:
input_features = list()
label = list()
for file in os.listdir(images_path):
    for image_file in os.listdir(images_path+'\\'+file):
        file_name,file_extension = os.path.splitext(image_file)
        if(file_extension in ['.png','.jpg']):
            img = load_img(images_path+'\\'+file+'\\'+image_file)
            print("1",img)
            img1 = img_to_array(img)
            print("2",img1)
            img1 = img1.astype('float32')
            #img2 = np.expand_dims(img1,axis=0)
            #img.shape[0]
            #print("3",img2)
            #img_encode = preprocess_input(img)
            #print("4",img)
            #img_encode = vgg_face(img2)
            #print("5",img_encode)
            input_features.append(img1)
            a = np.asarray(input_features,dtype=np.float32)
            label.append(file)
#return np.array(all_embedings),label_name

1 <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=128x128 at 0x22110DFECC0>
2 [[[ 23.  30.  23.]
  [ 25.  30.  24.]
  [ 29.  32.  25.]
  ...
  [ 31.  33.  30.]
  [ 35.  37.  34.]
  [ 37.  39.  38.]]

 [[ 21.  26.  19.]
  [ 23.  28.  21.]
  [ 28.  29.  21.]
  ...
  [ 36.  38.  37.]
  [ 34.  36.  35.]
  [ 34.  36.  35.]]

 [[ 23.  26.  15.]
  [ 26.  28.  17.]
  [ 30.  30.  18.]
  ...
  [ 40.  44.  43.]
  [ 30.  34.  33.]
  [ 24.  28.  27.]]

 ...

 [[252. 255. 248.]
  [253. 254. 246.]
  [253. 254. 246.]
  ...
  [ 32.  44.  44.]
  [ 28.  40.  40.]
  [ 29.  41.  41.]]

 [[253. 255. 247.]
  [254. 255. 247.]
  [254. 255. 245.]
  ...
  [ 49.  60.  62.]
  [ 41.  53.  53.]
  [ 39.  51.  51.]]

 [[253. 255. 247.]
  [254. 255. 245.]
  [254. 255. 243.]
  ...
  [ 72.  83.  85.]
  [ 60.  72.  72.]
  [ 49.  61.  61.]]]
1 <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=128x128 at 0x22110DE2FD0>
2 [[[246. 218. 207.]
  [245. 218. 207.]
  [242. 218. 208.]
  ...
  [ 26.  26.  16.]
  [ 23.  2

2 [[[177. 151. 126.]
  [119.  92.  65.]
  [ 98.  68.  42.]
  ...
  [196. 169. 140.]
  [186. 162. 138.]
  [156. 134. 111.]]

 [[158. 131. 104.]
  [112.  85.  58.]
  [116.  86.  60.]
  ...
  [172. 145. 116.]
  [190. 166. 140.]
  [177. 155. 132.]]

 [[142. 112.  86.]
  [107.  77.  51.]
  [113.  82.  54.]
  ...
  [169. 139. 111.]
  [191. 165. 140.]
  [194. 170. 146.]]

 ...

 [[  5.  10.   4.]
  [  6.   8.   5.]
  [ 10.   8.   9.]
  ...
  [182. 155. 144.]
  [181. 159. 148.]
  [222. 200. 189.]]

 [[  5.  10.   4.]
  [  8.  10.   7.]
  [ 11.   7.   6.]
  ...
  [181. 157. 147.]
  [198. 176. 165.]
  [245. 225. 216.]]

 [[  7.  12.   6.]
  [ 10.  10.   8.]
  [ 12.   8.   7.]
  ...
  [182. 158. 148.]
  [217. 197. 188.]
  [255. 246. 236.]]]
1 <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=128x128 at 0x22110DE27B8>
2 [[[108.  78.  54.]
  [106.  75.  54.]
  [108.  77.  56.]
  ...
  [124.  88.  66.]
  [121.  85.  63.]
  [114.  78.  56.]]

 [[109.  79.  55.]
  [103.  72.  51.]
  [100.  69.  4

1 <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=128x128 at 0x22110DFE668>
2 [[[ 56.  32.  28.]
  [ 49.  28.  23.]
  [ 42.  23.  17.]
  ...
  [ 35.  16.  18.]
  [ 28.  13.  16.]
  [ 26.  14.  16.]]

 [[ 56.  32.  28.]
  [ 47.  26.  21.]
  [ 39.  20.  14.]
  ...
  [ 31.  12.  14.]
  [ 30.  14.  17.]
  [ 29.  14.  17.]]

 [[ 53.  29.  25.]
  [ 47.  26.  21.]
  [ 42.  23.  19.]
  ...
  [ 27.   7.   8.]
  [ 30.  11.  13.]
  [ 29.  13.  14.]]

 ...

 [[125.  92.  61.]
  [124.  91.  60.]
  [124.  90.  62.]
  ...
  [115.  84.  55.]
  [117.  83.  55.]
  [118.  84.  56.]]

 [[124.  90.  62.]
  [124.  90.  62.]
  [125.  91.  63.]
  ...
  [115.  86.  54.]
  [114.  85.  53.]
  [114.  83.  52.]]

 [[122.  88.  60.]
  [125.  91.  63.]
  [127.  93.  66.]
  ...
  [114.  88.  55.]
  [114.  88.  55.]
  [113.  84.  52.]]]
1 <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=128x128 at 0x22110DF00F0>
2 [[[ 20.  12.  23.]
  [ 17.  11.  21.]
  [ 14.   9.  16.]
  ...
  [ 10.   9.  23.]
  [  9.   

2 [[[174. 128. 115.]
  [175. 129. 114.]
  [187. 138. 123.]
  ...
  [ 53.  73. 124.]
  [ 45.  70. 126.]
  [ 41.  70. 128.]]

 [[179. 133. 117.]
  [179. 133. 117.]
  [191. 142. 125.]
  ...
  [ 57.  77. 127.]
  [ 50.  75. 131.]
  [ 46.  75. 133.]]

 [[184. 142. 120.]
  [186. 141. 120.]
  [195. 149. 126.]
  ...
  [ 66.  84. 130.]
  [ 59.  82. 134.]
  [ 55.  82. 137.]]

 ...

 [[225. 234. 243.]
  [223. 237. 246.]
  [218. 243. 248.]
  ...
  [ 47.  39.  36.]
  [ 48.  38.  36.]
  [ 50.  39.  37.]]

 [[218. 224. 240.]
  [214. 226. 238.]
  [218. 238. 247.]
  ...
  [ 49.  41.  38.]
  [ 49.  39.  37.]
  [ 52.  41.  39.]]

 [[212. 217. 236.]
  [208. 217. 232.]
  [215. 233. 243.]
  ...
  [ 50.  42.  39.]
  [ 51.  40.  38.]
  [ 53.  42.  40.]]]
1 <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=128x128 at 0x22110DFEBE0>
2 [[[  4.   0.   0.]
  [  9.   4.   1.]
  [ 18.  10.   8.]
  ...
  [138.  85.  51.]
  [134.  84.  49.]
  [133.  83.  48.]]

 [[  4.   0.   0.]
  [  9.   4.   1.]
  [ 18.  10.   

2 [[[ 44.  44.  46.]
  [ 31.  32.  34.]
  [ 21.  27.  27.]
  ...
  [164. 143. 116.]
  [153. 128.  98.]
  [150. 121.  89.]]

 [[ 37.  35.  38.]
  [ 32.  33.  35.]
  [ 32.  38.  38.]
  ...
  [176. 154. 130.]
  [142. 117.  87.]
  [145. 116.  84.]]

 [[ 31.  29.  32.]
  [ 44.  44.  46.]
  [ 29.  33.  34.]
  ...
  [156. 134. 110.]
  [160. 134. 107.]
  [159. 130. 100.]]

 ...

 [[188. 142. 118.]
  [167. 121.  97.]
  [174. 128. 104.]
  ...
  [133.  95.  76.]
  [158. 123. 103.]
  [173. 141. 120.]]

 [[192. 146. 122.]
  [175. 131. 106.]
  [167. 123.  98.]
  ...
  [144. 108.  86.]
  [171. 136. 114.]
  [166. 134. 111.]]

 [[199. 155. 130.]
  [181. 137. 112.]
  [165. 121.  96.]
  ...
  [161. 125. 103.]
  [174. 139. 117.]
  [156. 124. 101.]]]
1 <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=128x128 at 0x22110DF00B8>
2 [[[ 83.  56.  27.]
  [ 83.  56.  29.]
  [ 86.  59.  32.]
  ...
  [191. 162. 130.]
  [199. 169. 135.]
  [199. 166. 133.]]

 [[ 88.  61.  32.]
  [100.  73.  46.]
  [110.  83.  5

2 [[[41. 50. 55.]
  [41. 50. 55.]
  [53. 58. 62.]
  ...
  [33. 36. 43.]
  [38. 41. 48.]
  [38. 42. 51.]]

 [[46. 55. 60.]
  [33. 41. 44.]
  [29. 34. 37.]
  ...
  [33. 33. 41.]
  [38. 41. 48.]
  [39. 44. 50.]]

 [[48. 58. 60.]
  [33. 41. 43.]
  [18. 23. 26.]
  ...
  [36. 37. 42.]
  [39. 42. 49.]
  [36. 39. 46.]]

 ...

 [[16. 16. 16.]
  [17. 17. 17.]
  [17. 17. 17.]
  ...
  [34. 32. 33.]
  [52. 50. 51.]
  [60. 58. 59.]]

 [[17. 17. 17.]
  [17. 17. 17.]
  [15. 15. 15.]
  ...
  [38. 38. 38.]
  [47. 45. 46.]
  [33. 31. 32.]]

 [[16. 16. 16.]
  [15. 15. 15.]
  [12. 12. 12.]
  ...
  [44. 44. 44.]
  [40. 40. 40.]
  [15. 13. 14.]]]
1 <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=128x128 at 0x22110DFE470>
2 [[[ 32.  27.  31.]
  [ 32.  27.  31.]
  [ 31.  26.  30.]
  ...
  [ 27.  27.  29.]
  [ 26.  26.  28.]
  [ 26.  26.  28.]]

 [[ 29.  24.  28.]
  [ 29.  24.  28.]
  [ 29.  24.  28.]
  ...
  [ 25.  25.  27.]
  [ 23.  23.  25.]
  [ 22.  22.  24.]]

 [[ 27.  22.  26.]
  [ 28.  23.  27.]
 

1 <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=128x128 at 0x22110DFE320>
2 [[[ 25.  29.  38.]
  [112. 116. 127.]
  [ 57.  61.  72.]
  ...
  [209. 222. 231.]
  [212. 225. 234.]
  [210. 223. 232.]]

 [[ 86.  90.  99.]
  [ 48.  52.  63.]
  [ 23.  27.  38.]
  ...
  [210. 223. 232.]
  [205. 218. 227.]
  [211. 224. 233.]]

 [[ 59.  63.  72.]
  [ 14.  18.  29.]
  [ 54.  61.  71.]
  ...
  [213. 226. 235.]
  [215. 228. 237.]
  [208. 221. 230.]]

 ...

 [[ 38.  25.  19.]
  [ 32.  21.  15.]
  [ 19.   6.   0.]
  ...
  [ 37.  22.  15.]
  [ 38.  23.  16.]
  [ 37.  20.  13.]]

 [[ 38.  23.  18.]
  [ 32.  21.  15.]
  [ 19.   8.   2.]
  ...
  [ 46.  31.  24.]
  [ 38.  24.  15.]
  [ 32.  18.   9.]]

 [[ 33.  18.  13.]
  [ 32.  19.  13.]
  [ 24.  13.   9.]
  ...
  [ 50.  36.  27.]
  [ 33.  19.  10.]
  [ 34.  21.  12.]]]
1 <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=128x128 at 0x22110DE2EB8>
2 [[[20. 20. 18.]
  [41. 41. 39.]
  [53. 53. 51.]
  ...
  [30. 31. 33.]
  [36. 37. 39.]
  [33.

In [12]:
a.shape

(89, 128, 128, 3)

In [13]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(label)

In [26]:
model.compile(loss='sparse_categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [27]:
model.fit(a,y,epochs = 50, validation_split =0.2,batch_size=5)

Train on 71 samples, validate on 18 samples
Epoch 1/50
 5/71 [=>............................] - ETA: 9s

InvalidArgumentError:  Incompatible shapes: [5,1] vs. [5,128,128]
	 [[node metrics/accuracy/Equal (defined at C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py:1751) ]] [Op:__inference_distributed_function_7110]

Function call stack:
distributed_function


In [16]:
model.save('face_5_celebs.h5')

In [29]:
np.save('face_recog_cnn_classifier_zee_nav.npy',le.classes_)